- linux/my_application.cc
|  | Before | After |
| --- | --- | --- |
| Default Size | ![Bildschirmfoto von 2022-01-31 18-54-18](https://user-images.githubusercontent.com/15329494/151846926-5e33d337-d337-4d51-8a77-070d4ffa925c.png) | ![Bildschirmfoto von 2022-01-31 18-51-09](https://user-images.githubusercontent.com/15329494/151847013-8b3aeb65-dd39-4ae2-b373-c94e9dd4416a.png) |
| Min Size | ![Bildschirmfoto von 2022-01-31 18-54-25](https://user-images.githubusercontent.com/15329494/151847201-c15e18dc-3eb3-4575-b7db-4a09246f7ad8.png) | ![Bildschirmfoto von 2022-01-31 18-51-18](https://user-images.githubusercontent.com/15329494/151847200-343b05eb-2f52-467f-9ebb-0dcefa6412e7.png) |
Closes #3
> GtkWindow: set min, max and default sizes

- .github/workflows/test.yaml
- integration_test/README.md
- integration_test/firmware_updater_test.dart
- pubspec.yaml
- test/test_utils.dart
Install `fwupd-tests`:
```sh
sudo apt install fwupd-tests
```
Notice the instructions at the end:
```
...
Setting up fwupd-tests (x.y.z) ...
To enable test suite, modify /etc/fwupd/daemon.conf
To enable test suite, enable fwupd-tests remote
```
Modify `/etc/fwupd/daemon.conf`:
```diff
diff --git a/etc/fwupd/daemon.conf b/etc/fwupd/daemon.conf
index 6ac8252..388a175 100644
--- a/etc/fwupd/daemon.conf
+++ b/etc/fwupd/daemon.conf
@@ -6,7 +6,7 @@ DisabledDevices=
-DisabledPlugins=test;test_ble;invalid
+DisabledPlugins=invalid
ArchiveSizeMax=0
```
Enable `fwupd-tests` remote:
```sh
fwupdmgr enable-remote fwupd-tests
```
> Add integration test based on fwupd-tests

- lib/firmware_model.dart
Some devices that only support version upgrades (as indicated by `FwupdDeviceFlag.onlyVersionUpgrade`) throw an `FwupdNotSupportedException` instead of an `FwupdNothingToDoException`, when trying to fetch the releases - catch both and log a debug message.
> fix bug due to uncaught FwupdNotSupportedException

- lib/firmware_model.dart
- lib/firmware_page.dart
- lib/src/widgets/device_header.dart
- lib/src/widgets/device_icon.dart
- lib/widgets.dart
- linux/my_application.cc
First part of the layout update (part of a smaller breakdown of #46):
- replace Scaffold with YaruMasterDetailPage
- fix redundant icons
- ensure FirmwareModel starts in loading state
> Layout update

- lib/src/l10n/app_en.arb
- lib/src/widgets/device_body.dart
- test/firmare_page_test.dart
Second part of the layout update (part of a smaller breakdown of #46):
- Show device flags as list instead of chips
- Move buttons to the top
> Update layout of device body

- lib/main.dart
- pubspec.yaml
YaruTheme API has been simplified a bit, and YaruMasterDetailPage has gained page transitions.
https://user-images.githubusercontent.com/140617/191014544-87a6fd23-6fdc-415e-8c32-b5e4b1d6706c.mp4
NOTE: Yaru 0.4 requires Flutter 3.3.
> Upgrade Yaru

- lib/device_model.dart
- lib/firmware_body_page.dart
- lib/firmware_page.dart
- lib/src/widgets/device_body.dart
- lib/src/widgets/release_dialog.dart
- test/device_model_test.dart
Show the release dialog as a page in the new layout. Design updates will follow.
* add `DeviceBodyPage` - renders the right pane in the master detail layout for each device
* add `DeviceModel` - view model for `DeviceBodyPage`
- provides `install()`, `verify()` for the device by calling the respective methods of the `FirmwareModel`
- keeps track of the currently selected release, `DeviceBodyPage` will respond accordingly
> Device release page

- integration_test/firmware_updater_test.dart
- lib/release_page.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/confirmation_dialog.dart
Small improvements for the confirmation dialogs:
* buttons now read "Upgrade", "Downgrade", "Reinstall" instead of "OK" (and the integration test is now able to distinguish the button in the dialog from the one on the page \o/)
* dialog shows a notice if the device won't be available during the action
> Improve dialogs

- lib/firmware_model.dart
With the 9 fwupd devices I have, it was logging 505 "nothing to do" messages during integration tests. :)
> Silence the "nothing to do" exceptions

- lib/firmware_body_page.dart
- lib/firmware_model.dart
I noticed that the version number didn't update after installing an update:
[Before](https://user-images.githubusercontent.com/113362648/191706995-a38ae013-b2fb-4da5-a2d6-555122bf7990.webm)
Fixed:
[After](https://user-images.githubusercontent.com/113362648/191707055-c6199d29-65f8-47f5-acd3-c81deebad396.webm)
> Bug fix: update device information after installing a new release

- lib/fwupd_service.dart
- test/fwupd_service_test.dart
A StreamController is not allowed to call add() while addStream().
> Bad state: Cannot add event while adding a stream
> FwupdService: fix stream handling

- lib/device_page.dart
- lib/firmware_body_page.dart
- lib/release_page.dart
access device properties and methods through provider instead of parameters and callbacks
> cleanup DevicePage and ReleasePage

- lib/device_model.dart
- lib/device_page.dart
- lib/firmware_model.dart
- lib/fwupd_x.dart
- lib/src/l10n/app_en.arb
- test/firmare_page_test.mocks.dart
- test/firmware_model_test.dart
* add `verifyUpdate` methods to `FirmwareModel` and `DeviceModel` (instructs the fwupd service to update a device's checksums)
* revert changes to `canVerify` method introduced in #65 - it should reflect the devices capability to verify a checksum, regardless of whether it currently has a checksum or not.
* add 'Update checksums button'
> Add button to update device checksums

- lib/release_page.dart
- remove the separator until scrolled under to give it less boxy looks
- ensure that the back button stays round
Close: #70
> ReleasePage: tweak app bar & back button looks

- lib/src/widgets/confirmation_dialog.dart
- test/widgets/message_dialog_test.dart
Make sure to always show the cancel button, even if `onCancel` is not provided.
|-|-|
| ![image](https://user-images.githubusercontent.com/113362648/195122350-5e26eb7f-02a9-48d7-a9db-01e9bd095424.png) | ![image](https://user-images.githubusercontent.com/113362648/195121915-868ce074-d21d-40db-8c8d-b2efce5082a8.png) |
> always show cancel button on confirmation dialog

- lib/detail_page.dart
- lib/device_model.dart
- lib/device_tile.dart
- lib/fwupd_notifier.dart
- lib/fwupd_service.dart
- lib/release_page.dart
- pubspec.yaml
- test/firmware_app_test.mocks.dart
- test/fwupd_service_test.mocks.dart
- test/test_utils.mocks.dart
Workarounds for some issues with fwupd 1.7.5 in ubuntu 22.04:
- `FwupdClient` doesn't return to `FwupdStatus.idle` after installing a release but remains in `FwupdStatus.unknown`. The underlying property on DBus is changed, but no corresponding signal is sent.
Fix: force `FwupdClient` to re-read all DBus properties and update its cache (using [this fork](https://github.com/d-loose/fwupd.dart/tree/refresh-property-cache)).
- fwupd doesn't always send correct `DeviceChanged` signals after installing a release.
Fix: call `DeviceStore.refresh()` after install (maybe this is overkill?)
> Fwupd workarounds

- lib/device_page.dart
- lib/firmware_app.dart
- lib/release_page.dart
- lib/src/widgets/app_progress_bar.dart
- lib/src/widgets/device_header.dart
- pubspec.yaml
- test/firmware_app_test.dart
- test/widgets/app_progress_bar_test.dart
~~WIP~~
I'm testing the updated Yaru widgets to see if we can use them to improve the UI.
- use new `YaruMasterDetailPage`, `YaruMasterTile`, `YaruDetailPage`
- use `AppProgressBar` in `DevicePage` (and a simple `AppBar` in `ReleasePage` for now)
~~Current state:~~
~~[Screencast from 11-10-22 16:18:14.webm](https://user-images.githubusercontent.com/113362648/195116642-6ed17876-e3c4-4cc1-922c-7c670b66bf56.webm)~~
> Use updated Yaru Widgets

- lib/firmware_app.dart
- lib/fwupd_notifier.dart
- lib/fwupd_service.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/error_banner.dart
- lib/widgets.dart
- test/firmware_app_test.dart
- test/firmware_app_test.mocks.dart
- test/fwupd_notifier_test.dart
- test/fwupd_service_test.dart
- test/test_utils.dart
Another WIP. Adds a closable warning message when running on battery power.
- add `ErrorBanner` widget
- access upower's `onBattery` through `FwupdNotifier`
I've abused the existing `_propertiesChanged` controller to send upower's changed properties alongside those of fwupd - is this a terrible idea?
There's also still a small bug that might be of more general interest: when the UI renders before `FwupdService.init()` finishes a default `onBattery` state of `false` is reported, even if that's not the case. So we should somehow avoid this race condition and make sure all DBus properties of all services are set before trying to read them.
> Battery warning

- snap/snapcraft.yaml
Needed for the battery warning to work in the snap
> add upower interface to snapcraft.yaml

- lib/detail_page.dart
- lib/device_page.dart
- lib/release_page.dart
- linux/my_application.cc
- test/firmware_app_test.dart
- test/test_utils.dart
- allow `YaruMasterDetailPage` to collapse into portrait layout
- add `YaruBackButton` to navigate back to tile in portrait layout
- also use `YaruBackButton` instead of the default material button in `ReleasePage`
Please let me know if there's a better way to handle the nested navigators - currently I'm passing the portrait layout's navigator as a parameter to `DevicePage`, which is wrapped in a navigator itself to show the `ReleasePage`.
Somehow Ubuntu's screen recorder has been acting weird these days, so some screenshots will have to do:
> Portrait layout

- lib/device_model.dart
- lib/fwupd_service.dart
- test/device_model_test.dart
- test/fwupd_notifier_test.dart
- test/fwupd_service_test.dart
- test/test_utils.dart
- test/test_utils.mocks.dart
I've added a few missing tests for `FwupdNotifier`, `FwupdService` and `DeviceModel`.
`FwupdService` now consistently uses `FwupdDevice`s as parameters (some methods used `String deviceId`)
> Improve test coverage

- lib/device_model.dart
- lib/device_page.dart
- lib/firmware_app.dart
- lib/fwupd_service.dart
- lib/release_page.dart
- lib/src/widgets/confirmation_dialog.dart
- test/device_model_test.dart
- test/device_page_test.dart
- test/device_page_test.mocks.dart
- test/firmware_app_test.dart
- test/fwupd_service_test.dart
- test/test_utils.dart
- test/test_utils.mocks.dart
- test/widgets/message_dialog_test.dart
I've removed the error handling from the `DeviceModel` and moved it directly to `FwupdService`. There are now two callbacks to display errors and get user confirmations that are called on `FwupdExceptions` during `install()` and before invoking `reboot()`, respectively. `FirmwareApp` then shows the dialogs through these callbacks.
~~Still WIP - need to add remaining tests.~~
> Improve error handling

- integration_test/firmware_updater_test.dart
- lib/firmware_app.dart
- lib/main.dart
- pubspec.yaml
- test/firmware_app_test.dart
gtk_application.dart won't be able to deliver local command-line arguments but the new property was added to help with passing the arguments around so that the handling of local vs. remote command-line arguments can be easily unified.
> Use GtkApplicationNotifier.commandLine

- linux/my_application.cc
- packages/firmware_notifier/bin/firmware_notifier.dart
- packages/firmware_notifier/pubspec.yaml
- override `command_line` instead of `local_command_line` in my_application.cc to preserve default command line handler for DBus signals (i.e. correct behavior on --gapplication-service).
> call 'CommandLine' DBus method to invoke firmware-updater from the notifier

- .github/workflows/build.yaml
- .github/workflows/snap.yaml
speed up PR workflow by moving snap build to a daily cron job
> CI: run snap build as cron

- launcher-script/bin/launch-firmware-updater.sh
- snap/snapcraft.yaml
uses a helper script to launch the desktop application, which currently needs to be a user daemon to work with DBus activation in the snap, see #120
> DBus activation in the snap

- lib/src/widgets/device_icon.dart
it's provided by YaruFreedesktopIcons as part of the standard application icons
> remove preferences-desktop-keyboard from extraIcons

- lib/device_page.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/small_chip.dart
- lib/src/widgets/status_banner.dart
due to new AppLocalization features in flutter 3.3.10 'selected' can't be used as a placeholder name any more
Edit: flutter 3.3.10 also complains about deprecation of `TextTheme.caption`
> rename localization placeholders

- snap/snapcraft.yaml
- pass `--gapplication-service` in app command to ensure correct DBus behavior
- add timer to firmware-notifier
> Run notifier periodically via snapd service timer

- lib/firmware_app.dart
- lib/src/l10n/app_en.arb
- pubspec.yaml
- test/firmware_app_test.dart
Use new `emptyBuilder` in yaru_widgets to show a message rather than causing an exception.
This obviously needs some UI work :)
Fix #161
> Handle empty device list gracefully

- pubspec.yaml
See also: https://github.com/canonical/ubuntu-flutter-plugins/pull/225
> chore: use published version of ubuntu_logger

- integration_test/firmware_updater_test.dart
- lib/release_page.dart
- lib/src/l10n/app_en.arb
- test/release_page_test.dart
Ref #177 
UDENG-703
@elioqoshi I'm splitting the UI updates into small components so it's easier to iterate when necessary - please ignore everything besides the expandable in the screen cast :)
[Screencast from 2023-06-13 18-08-19.webm](https://github.com/canonical/firmware-updater/assets/113362648/32db1e5a-e313-49b5-9b69-142719cdb0ab)
> feat(release_page): hide old versions in expandable

- lib/src/widgets/device_header.dart
- lib/src/widgets/release_card.dart
Ref #177 
UDENG-703
@elioqoshi I'm using [material design's `Badge`](https://m3.material.io/components/badges/overview) here. By default it seems to be slightly smaller than what you have in your designs - what do you think?
> feat: use colored circle badge for updates

- lib/src/widgets/release_card.dart
Ref #177 
UDENG-703
Moved the buttons up and made them all `FilledButton`s.
~~The 'Current Version' `Chip` still needs some theming.~~
|Dark|Light|
|-|-|
|![image](https://github.com/canonical/firmware-updater/assets/113362648/31d38a7b-2378-4c58-91ed-ca0b98c22342)|![image](https://github.com/canonical/firmware-updater/assets/113362648/82ee5ad5-a47e-40c1-8a07-f82840058144)|
> feat(release_card): update UI

- snap/snapcraft.yaml
Which is a pre-required to be able to publish to stable
> Change the snapcraft grade to stable

- assets/firmware-updater.desktop
It looks like we had some left over strings based on the installer snap.  This should be clearly for a firmware updater
> Improved the strings in the desktop file

- lib/device_page.dart
- lib/main.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/release_card.dart
- test/device_page_test.dart
In this PR:
- Updating the icon on the update firmware confirmation dialog
- Making the device name bold on the checksum confirmation dialog
- Overriding the Yaru theme to force the green accent theme.
- Removing some padding, so some content is align with the rest of the content on the device page.
Screenshots:
> feat: updating the UIs

- packages/firmware_updater/lib/device_page.dart
In this PR:
- Switching an icon when updating firmware. 
Before:
After:
> feat: switching to the right icon when updating firmware

- CONTRIBUTING.md
In this PR:
- Adding a classic `CONTRIBUTING.md` for guidelines for future contributors.
> docs: adding contributing.md for future contributors.

- snap/snapcraft.yaml
Enables `arm64` in the snapcraft.yaml
> feat: enable arm64 builds

- packages/firmware_notifier/lib/firmware_notifier.dart
- packages/firmware_notifier/test/firmware_notifier_test.dart
- packages/firmware_updater/lib/device_store.dart
- packages/firmware_updater/test/device_store_test.dart
- packages/firmware_updater/test/test_utils.dart
> fix: handle errors when fwupd detects no devices

- packages/firmware_updater/lib/main.dart
- packages/firmware_updater/pubspec.yaml
Copy the same logfile location as app-center:
~/.local/share/$NAME
which inside snap resolves to:
/home/$USER/snap/$NAME/current/.local/share/$NAME
Also remove the debug level logic because that duplicates the
default behaviour.
Fixes: #242
> fix: Move logfile to snap-friendly location

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Adds issue templates for bug reports and enhancement.
You can preview what these options look like on my branch [here](https://github.com/matthew-hagemann/firmware-updater/issues/new/choose)
>  Feat: add issue templates

- apps/firmware_updater/lib/l10n/app_en.arb
- apps/firmware_updater/lib/widgets/dialogs.dart
- apps/firmware_updater/pubspec.lock
- apps/firmware_updater/pubspec.yaml
I added a text widget with the link color and a gesture detector, since I couldn't get the `Html` widget we use elsewhere to work within the dialog:
```
The following assertion was thrown during performLayout():
The RenderCSSBox class does not implement "computeDryBaseline".
If you are not writing your own RenderBox subclass, then this is
not
your fault. Contact support:
https://github.com/flutter/flutter/issues/new?template=2_bug.yml
The relevant error-causing widget was:
AlertDialog
```
UDENG-6588
> feat: add FDE documentation link to confirmation dialog

- apps/firmware_updater/lib/widgets/dialogs.dart
- apps/firmware_updater/test/device_page_test.dart
- apps/firmware_updater/test/release_page_test.dart
- apps/firmware_updater/test/test_utils.dart
- apps/firmware_updater/test/widgets/message_dialog_test.dart
While continuing with the e2e tests, I realized that we still need to show a checkbox for `UEFI dbx` updates in the case of Bitlocker or any other non-Ubuntu FDE. I've also adapted the widget tests to be more explicit.
> fix: show checkbox for UEFI dbx updates with non Ubuntu FDE

- apps/firmware_updater/lib/pages/device_page.dart
See #362 - we shouldn't manually compare version strings if we have access to a flag that indicates whether an update is available or not.
> fix: rely on FWUPD_RELEASE_FLAG_IS_UPGRADE for 'update available' chip
