- snap/snapcraft.yaml
Updated to core20 and build necessary bits to support recent code changes
> Updated to core20

- lib/model.dart
- pubspec.yaml
FwupdClient.install() was added in canonical/fwupd.dart#14
> Upgrade to fwupd.dart 0.2 & adapt to changes

- pubspec.yaml
https://pub.dev/packages/yaru_widgets
> Use a published version of yaru_widgets

- lib/firmware_page.dart
- lib/src/widgets/refresh_button.dart
- test/firmare_page_test.dart
> use YaruCircularProgressIndicator

- integration_test/firmware_updater_test.dart
- lib/device_page.dart
- lib/firmware_body_page.dart
- lib/release_page.dart
- lib/src/widgets/device_body.dart
- lib/src/widgets/release_body.dart
- lib/widgets.dart
Replace the release dialog with a proper page.
> Release page update

- lib/release_page.dart
- lib/src/widgets/option_card.dart
|---|---|
| ![Screenshot from 2022-09-21 13-27-57](https://user-images.githubusercontent.com/140617/191495258-5a9c5318-298e-4797-9b47-88ea02e1cca7.png) | ![Screenshot from 2022-09-21 13-40-27](https://user-images.githubusercontent.com/140617/191495267-bfd6e0e6-7b33-4bb5-9b90-c6708e6242dc.png) |
> Add horizontal padding for release cards

- lib/firmware_body_page.dart
[firmware-updater-page-transitions.webm](https://user-images.githubusercontent.com/140617/191685277-97e58b6e-123b-447c-954d-bea78fe433bd.webm)
> Use horizontal transitions for the release page

- integration_test/firmware_updater_test.dart
test checksum update through the UI, assumes that no checksum is currently stored for the fake webcam (i.e. fwupd needs to be restarted before running the test locally)
> test checksum update in integration test

- lib/detail_page.dart
- lib/firmware_page.dart
It builds the "detail" part of the master-detail layout.
> Rename FirmwareBodyPage to DetailPage

- lib/detail_page.dart
- lib/device_model.dart
- lib/device_store.dart
- lib/firmware_app.dart
- lib/main.dart
- linux/my_application.cc
- pubspec.yaml
- test/device_store_test.dart
- test/firmware_app_test.dart
- test/firmware_app_test.mocks.dart
This adds two command line parameters (device id and release version) that can be used to instruct the firmware updater to navigate to a specific device/release.
https://user-images.githubusercontent.com/113362648/197556693-4859063c-fc81-4706-8c66-de6bd2a9aacb.mp4
> Command line args

- packages/firmware_notifier/bin/firmware_notifier.dart
- snap/snapcraft.yaml
Just to show that this works now :)
(assumes that the firmware-updater binary can be found in PATH)
https://user-images.githubusercontent.com/113362648/197782811-185df44a-2b16-489f-92f5-5bae4cd6060b.mp4
> call updater from notifier

- lib/firmware_app.dart
- lib/fwupd_notifier.dart
- lib/fwupd_service.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/confirmation_dialog.dart
- test/firmware_app_test.dart
- test/fwupd_notifier_test.dart
- test/fwupd_service_test.mocks.dart
- test/test_utils.dart
- test/test_utils.mocks.dart
Adds message dialogs that inform the user about device requests.
> Device requests

- lib/detail_page.dart
- lib/device_model.dart
- lib/device_page.dart
- lib/device_store.dart
- lib/firmware_app.dart
- lib/release_page.dart
- lib/src/widgets/release_card.dart
- test/device_page_test.dart
- test/device_page_test.mocks.dart
- test/device_store_test.dart
- test/firmware_app_test.dart
- test/firmware_app_test.mocks.dart
~~WIP~~
Replaces the selectable release tiles with a list of `YaruSection`s that have their individual Upgrade/Reinstall/Downgrade.
> Update release page UI

- lib/src/widgets/device_icon.dart
- pubspec.yaml
Adds @Jupi007's [new icons](https://github.com/ubuntu/yaru_icons.dart/pull/88).
Closes #125
> add new yaru device icons

- lib/firmware_app.dart
- lib/src/widgets/release_card.dart
- pubspec.yaml
| - | - |
| ![image](https://user-images.githubusercontent.com/113362648/203323447-f1549919-11a4-4e00-bd67-40f9a80d4341.png) | ![image](https://user-images.githubusercontent.com/113362648/203322578-d3a9b94b-1b55-4e7b-b86b-d61ebc4da0c4.png) |
> use new yaru widgets release and improve release card layout

- lib/src/widgets/release_card.dart
| - | - |
| ![image](https://user-images.githubusercontent.com/113362648/203560006-185b40fc-39ff-4d77-be0a-f076bf36dbaa.png) | ![image](https://user-images.githubusercontent.com/113362648/203559820-bb694474-465f-4e58-aa5b-a7b53759e25b.png) |
> fix release card alignment

- linux/my_application.cc
| - | - |
| ![image](https://user-images.githubusercontent.com/113362648/203834541-be59c51a-4b4b-4a08-835d-f054bd56850d.png) | ![image](https://user-images.githubusercontent.com/113362648/203834437-762cf131-6757-4369-ac2d-3a8c43c9eaa1.png) |
Close #135
> use more appropriate default window size

- lib/firmware_app.dart
- lib/src/widgets/device_icon.dart
- pubspec.yaml
- test/firmware_app_test.dart
* Update to yaru_icons 1.0.0
- Use `YaruFreedesktopIcons`
- Keep list with additional icons as fallback
* Update to yaru_widgets 2.0.0-beta3
- Use `YaruPageController`
> Update yaru icons and widgets

- lib/src/widgets/error_banner.dart
| | Before | After |
|---|---|---|
| Light | ![image](https://user-images.githubusercontent.com/140617/220102134-4fe2e8ed-96bc-4251-9a15-86e9774bc13f.png) | ![image](https://user-images.githubusercontent.com/140617/220101962-a5f4bab9-a972-4221-82b7-04d8b185f049.png) |
| Dark | ![image](https://user-images.githubusercontent.com/140617/220102238-9537d674-23f1-4573-bc3d-3637667d6050.png) | ![image](https://user-images.githubusercontent.com/140617/220101924-4a7bc5b2-4c18-41d3-925f-f5d65052cb16.png) |
> ErrorBanner: update colors

- lib/device_page.dart
- lib/firmware_app.dart
- lib/release_page.dart
- linux/my_application.cc
Does centering the title on the right make it better or worse? I think the space between the icon and the name looks a bit weird.
[Screencast from 2023-02-22 12-28-15.webm](https://user-images.githubusercontent.com/113362648/220607579-e0211760-a83a-4d9d-8993-27692f5adf23.webm)
Fix #154
> use YaruWindowTitleBar

- lib/fwupd_service.dart
- test/fwupd_service_test.dart
I'm open to suggestions for a more detailed user-agent string :)
Close #178
> fix(download): use user-agent 'firmware-updater'

- integration_test/firmware_updater_test.dart
- pubspec.yaml
- test/test_utils.dart
Hopefully this resolves recent integration test issues in the CI.
> test: use pumpUntil from ubuntu_test

- .github/workflows/analysis.yaml
- .github/workflows/build.yaml
- .github/workflows/generate.yaml
- melos.yaml
- flutter pub run -> dart run
- expose flutter pub "$@"
> chore(melos): update config

- lib/detail_page.dart
- lib/release_page.dart
Before:
[Screencast from 2023-06-29 15-56-42.webm](https://github.com/canonical/firmware-updater/assets/113362648/fad7c9b3-1cd0-49a7-87c0-6fb9acc937ed)
After:
[Screencast from 2023-06-29 15-55-55.webm](https://github.com/canonical/firmware-updater/assets/113362648/02dcac0c-0b78-4d20-badf-1d8a11981942)
> fix: keep title bar in place during transitions

- integration_test/firmware_updater_test.dart
- lib/device_model.dart
- lib/device_page.dart
- lib/device_tile.dart
- lib/src/l10n/app_en.arb
- test/device_page_test.dart
- test/test_utils.dart
- test/test_utils.mocks.dart
Ref #177 
UDENG-703
* Moved the buttons around and adjusted labels
* Added 'Update to Latest' button
* Added 'Latest Version' (still a bit tentative, since releases provided by are not guaranteed to be sorted, but are sorted in practice 99.99% of the time)
* Changed 'All Versions' button style from 'Outlined' to 'Filled'
* Added 'Update Available' chip
|Light|Dark|
|-|-|
|![Screenshot from 2023-06-29 14-13-34](https://github.com/canonical/firmware-updater/assets/113362648/a9172765-5559-49e7-9a4e-9cec6421b3a0)|![Screenshot from 2023-06-29 14-13-26](https://github.com/canonical/firmware-updater/assets/113362648/2733fb5f-de6a-4610-9c52-fe3b87d6f57b)|
> feat(device_page): update UI

- integration_test/firmware_updater_test.dart
- lib/device_page.dart
- lib/src/l10n/app_en.arb
- lib/src/widgets/confirmation_dialog.dart
- lib/src/widgets/release_card.dart
- pubspec.yaml
- test/device_page_test.dart
Ref #177 
UDENG-703
|Light|Dark|
|-|-|
|![Screenshot from 2023-06-28 16-40-21](https://github.com/canonical/firmware-updater/assets/113362648/7dab04f9-f7b7-4991-aecf-0556fc2d615d)|![Screenshot from 2023-06-28 16-40-09](https://github.com/canonical/firmware-updater/assets/113362648/0084c788-cddc-4ef7-b70c-82844e500c57)|
[Screencast from 2023-06-28 16-40-48.webm](https://github.com/canonical/firmware-updater/assets/113362648/7e988cee-6404-4531-951a-d942273b6345)
> feat: implement new modal design

- lib/device_page.dart
- test/device_page_test.dart
> fix: show correct version in confirmation dialog

- packages/firmware_updater/lib/fwupd_dbus_service.dart
- packages/firmware_updater/test/fwupd_dbus_service_test.dart
- packages/firmware_updater/test/test_utils.mocks.dart
> feat: make user agent string comply with LVFS requirements

- .github/workflows/ci.yaml
> ci: add tics job

- apps/firmware_updater/lib/app/firmware_app.dart
- apps/firmware_updater/lib/l10n/app_en.arb
- apps/firmware_updater/lib/pages/device_page.dart
- apps/firmware_updater/lib/widgets/dialogs.dart
- apps/firmware_updater/lib/widgets/release_card.dart
- apps/firmware_updater/test/device_page_test.dart
- apps/firmware_updater/test/widgets/message_dialog_test.dart
The title overflows in a bit of an ugly way which isn't great but this gets us the functionality we need for the TPM FDE work.
UDENG-5815
> feat: highlighting the need for FDE recovery keys before installing firmware

- apps/firmware_updater/lib/main.dart
Adds missing high contrast themes
> feat: add high contrast theme

- apps/firmware_updater/pubspec.lock
- apps/firmware_updater/pubspec.yaml
- apps/firmware_updater/test/recovery_key_service_test.mocks.dart
Removes the git dependency used during the TPM FDE spike
> chore: use snapd 0.7.2
